name: "Sample React CI pipeline /workflow"

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Check Node version"
        run: node --version
      
      - name: "Clone the repository"
        uses: actions/checkout@v4         # used to fetch the code from the repository

      - name: "Install dependencies"
        run: npm install                   # installs the project dependencies

      - name: "Run tests"
        run: npm test                      # runs the test suite  

      - name: "Build the project"
        run: npm run build                 # builds the React project for production  

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist                     # uploads the build artifacts for later use  