name: "Sample React CI pipeline / workflow"

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Check Node version"
        run: node --version
      
      - name: "Clone the repository"
        uses: actions/checkout@v2         # used to fetch the code from the repository